### PR TITLE
Fix #424, spinner no longer speeds up when restarted

### LINKED ISSUE #424: Spinner start() should have no effect if already spinning
If you go to this [Plunker of the Spinner](http://plnkr.co/edit/j5M6EseO6DNmEbwSIdK3?p=preview) and click on "Start spinner" multiple times, the spinner goes faster and faster and the "Stop spinner' button no longer works. Have I done something incorrect in the setup, or is this a bug?

### PR DESCRIPTION
**Pull request by chrisahhh**
If `setInterval` is called multiple times then there will be multiple intervals animating the spinner, which makes it look faster

Added clearInterval, to clear the previous interval

### CODE REVIEW

File: src/components/Spinner/Spinner.js [hunk 1]
```diff
@@ -34,6 +34,7 @@ fabric.Spinner = function(target) {
      * @memberOf fabric.Spinner
      */
     function start() {
+        clearInterval(interval);
```
Comment (wdo3650) [inline src/components/Spinner/Spinner.js]: There's a stop() method in the code you can call that clears this interval. That would be great if you could swap this clearInterval out and call stop() in its place.

**Comment by wdo3650** [comment]
Thanks @chrisahh, this looks great! Approved.

**Comment by Jahnp** [comment]
Looks awesome! Thanks for fixing this, @chrisahhh :) We'll go ahead and merge this in.
